"""add workspaces & user_workspaces

Revision ID: 22ce796667e1
Revises: ce9e484f27fb
Create Date: 2026-09-15 18:25:56.104422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ce796667e1'
down_revision: Union[str, Sequence[str], None] = 'ce9e484f27fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=100), nullable=False, comment='业务空间名称'),
    sa.Column('path', sa.String(length=512), nullable=False, comment='工作目录路径'),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_index(op.f('ix_workspaces_name'), 'workspaces', ['name'], unique=True)
    op.create_table('user_workspaces',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('permission', sa.Enum('ADMIN', 'EDITOR', 'VIEWER', name='workspacepermission', native_enum=False, length=20), nullable=False, comment='该用户在该空间的权限'),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_workspaces_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_user_workspaces_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_workspaces')),
    sa.UniqueConstraint('user_id', 'workspace_id', name='uq_user_workspaces_user_workspace')
    )
    op.create_index(op.f('ix_user_workspaces_user_id'), 'user_workspaces', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_workspaces_workspace_id'), 'user_workspaces', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_workspaces_workspace_id'), table_name='user_workspaces')
    op.drop_index(op.f('ix_user_workspaces_user_id'), table_name='user_workspaces')
    op.drop_table('user_workspaces')
    op.drop_index(op.f('ix_workspaces_name'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
