"""add users.is_super

Revision ID: 636fdf346107
Revises: ed40a1145bb5
Create Date: 2026-09-15 20:14:10.266306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636fdf346107'
down_revision: Union[str, Sequence[str], None] = 'ed40a1145bb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_super', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='超级用户，只能直接改库'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_super')
    # ### end Alembic commands ###
