"""add public_workspaces & user_public_workspaces

Revision ID: 89f54e43803a
Revises: 636fdf346107
Create Date: 2026-09-20 14:05:32.606218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f54e43803a'
down_revision: Union[str, Sequence[str], None] = '636fdf346107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_workspaces',
    sa.Column('name', sa.String(length=100), nullable=False, comment='公共空间名称，agent 挂载路径 /public/{name}/ 的一部分，不可变'),
    sa.Column('description', sa.String(length=512), nullable=False, comment='给人看的说明，出现在 REST 列表里；不注入 system prompt（见 docs/adr 与 Q17 约定）'),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_public_workspaces'))
    )
    op.create_index(op.f('ix_public_workspaces_name'), 'public_workspaces', ['name'], unique=True)
    op.create_table('user_public_workspaces',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('public_workspace_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['public_workspace_id'], ['public_workspaces.id'], name=op.f('fk_user_public_workspaces_public_workspace_id_public_workspaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_public_workspaces_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_public_workspaces')),
    sa.UniqueConstraint('user_id', 'public_workspace_id', name='uq_user_public_workspaces_user_public_workspace')
    )
    op.create_index(op.f('ix_user_public_workspaces_public_workspace_id'), 'user_public_workspaces', ['public_workspace_id'], unique=False)
    op.create_index(op.f('ix_user_public_workspaces_user_id'), 'user_public_workspaces', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_public_workspaces_user_id'), table_name='user_public_workspaces')
    op.drop_index(op.f('ix_user_public_workspaces_public_workspace_id'), table_name='user_public_workspaces')
    op.drop_table('user_public_workspaces')
    op.drop_index(op.f('ix_public_workspaces_name'), table_name='public_workspaces')
    op.drop_table('public_workspaces')
    # ### end Alembic commands ###
