"""create users table

Revision ID: ce9e484f27fb
Revises: 
Create Date: 2026-09-13 19:31:34.923152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9e484f27fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('account', sa.String(length=50), nullable=False, comment='登录账号'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱，也可用于登录'),
    sa.Column('hashed_password', sa.String(length=100), nullable=False, comment='bcrypt 哈希'),
    sa.Column('refresh_token', sa.String(length=512), nullable=True, comment='当前有效的 refresh token，登录/刷新时轮换，登出后置空'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否启用'),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_account'), 'users', ['account'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_account'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
