"""路由的请求 / 响应模型（pydantic），按资源分文件。"""

from .auth import (
    LoginRequest,
    RefreshRequest,
    RegisterRequest,
    TokenPair,
    UserOut,
)
from .chat import (
    ChatApprove,
    ChatDeleteFiles,
    ChatDeleteMessages,
    ChatHistoryOut,
    ChatMessageOut,
    ChatRunOut,
    ChatSend,
    ChatStateOut,
    ChatStop,
    ChatStopOut,
    ChatThreadOut,
    ChatThreadsOut,
)
from .kb import (
    KbEntry,
    KbFileRef,
    KbList,
    KbListOut,
    KbReadOut,
    KbStored,
    KbUploadItem,
    KbUploadOut,
    KbWrite,
    Layer,
)
from .memory import (
    MemoryListOut,
    MemoryOut,
    MemoryPath,
    MemoryStored,
    MemoryUploadItem,
    MemoryUploadOut,
    MemoryWrite,
)
from .microservice import (
    MicroserviceCreate,
    MicroserviceGrant,
    MicroserviceListOut,
    MicroserviceOut,
)

__all__ = [
    "ChatApprove",
    "ChatDeleteFiles",
    "ChatDeleteMessages",
    "ChatHistoryOut",
    "ChatMessageOut",
    "ChatRunOut",
    "ChatSend",
    "ChatStateOut",
    "ChatStop",
    "ChatStopOut",
    "ChatThreadOut",
    "ChatThreadsOut",
    "KbEntry",
    "KbFileRef",
    "KbList",
    "KbListOut",
    "KbReadOut",
    "KbStored",
    "KbUploadItem",
    "KbUploadOut",
    "KbWrite",
    "Layer",
    "LoginRequest",
    "MemoryListOut",
    "MemoryOut",
    "MemoryPath",
    "MemoryStored",
    "MemoryUploadItem",
    "MemoryUploadOut",
    "MemoryWrite",
    "MicroserviceCreate",
    "MicroserviceGrant",
    "MicroserviceListOut",
    "MicroserviceOut",
    "RefreshRequest",
    "RegisterRequest",
    "TokenPair",
    "UserOut",
]
